name: CI Java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Descarga codigo
        run: ls -ltr
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean :service-a:build
      - name: Validate
        run: |
          ls -lt $GITHUB_WORKSPACE
          ls -lt $GITHUB_WORKSPACE/service-a/build/libs
